baseURL = 'https://dudung.github.io/bug2'
languageCode = 'en-us'
title = 'bug 2'
theme = 'default'

enableEmoji = true

ignoreErrors = ['error-missing-instagram-accesstoken']

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = 'Home'
  weight = 2
  identifier = 'home'
  url = '/'

[[menu.main]]
  name = 'Tags'
  weight = 1
  identifier = 'tags'
  url = '/tags'
